git-update: show a toast notification on Windows 8/10
This is a much less intrusive way to notify the user of any updates than
to pop up a modal dialog.

This addresses https://github.com/git-for-windows/git/issues/1335

Signed-off-by: Johannes Schindelin <johannes.schindelin@gmx.de>

diff --git a/git-extra/git-update b/git-extra/git-update
--- a/git-extra/git-update
+++ b/git-extra/git-update
@@ -112,7 +112,7 @@ git_update () {
 		--testing) testing=t; shift; continue;;
 		*) echo "Unknown option: $1" >&2;;
 		esac
-		printf >&2 '%s\n%s\n\t%s\n%s\n' \
+		printf >&2 '%s\n%s\n\t%s\n\t%s\n' \
 			"Usage: git-update [options]" \
 			"Options:" \
 			"-g, --gui Use GUI instead of terminal to prompt" \
@@ -123,6 +123,17 @@ git_update () {
 	case "$(uname -m)" in
 	x86_64) bit=64;;
 	*) bit=32;;
+	esac
+
+	try_toast=
+	test -z "$use_gui" ||
+	case "$(uname -s)" in
+	*-6.[23]|*-10.0)
+		# Only try to show a Toast notification on Windows 8 & 10,
+		# and only if we have a working wintoast.exe
+		! type wintoast.exe >/dev/null 2>&1 ||
+		try_toast=t
+		;;
 	esac
 
 	releases_url=https://api.github.com/repos/git-for-windows/git/releases
@@ -174,7 +185,42 @@ git_update () {
 		else
 			warn=" (killing $other_bashes Git Bash instances)"
 		fi
-		if test -n "$use_gui"
+		if test -n "$try_toast"
+		then
+			wintoast.exe --appname "Git for Windows" \
+				--appid GitForWindows.Updater \
+				--image /mingw$bit/share/git/git-for-windows.ico \
+				--text "Download and install $name$warn?" \
+				--action Yes --action No --expirems 15000
+			case $? in
+			0|16)
+				# clicked toast, or clicked Yes: download
+				;;
+			1|17)
+				# dismiseed, or clicked No: ignore this release
+				git config --global \
+					winUpdater.recentlySeenVersion "$latest"
+				return 1
+				;;
+			4|5|6|9|10)
+				# toast not activated, failed, toasts
+				# unsupported, WinToast init failed or toast
+				# not launched: fall back to using GUI
+				git gui--askyesno \
+					--title "Git Update Available" \
+					"Download and install $name$warn?" || {
+				    git config --global \
+					winUpdater.recentlySeenVersion "$latest"
+				    return 1
+				}
+				;;
+			*)
+				# toast timed out, or hidden, or unknown
+				# failure: ignore
+				return 1
+				;;
+			esac
+		elif test -n "$use_gui"
 		then
 			git gui--askyesno --title "Git Update Available" \
 				"Download and install $name$warn?" || {
